package scanner

import (
	"bufio"
	"bytes"
	"io"
	"os"
	"strings"
	"sync"

	"github.com/mohsinkaleem/dirloc/types"
)

const defaultMaxBuf = 1024 * 1024 // 1MB line buffer

// headSize is how much of a file is inspected for binary content and generated-code markers.
const headSize = 1024

var generatedMarkers = [][]byte{
	[]byte("code generated"),
	[]byte("do not edit"),
	[]byte("@generated"),
	[]byte("autogenerated"),
	[]byte("auto-generated"),
}

// isGenerated reports whether a file header carries a common generated-code marker.
func isGenerated(head []byte) bool {
	var lower [headSize]byte
	n := copy(lower[:], head)
	for i, c := range lower[:n] {
		if 'A' <= c && c <= 'Z' {
			lower[i] = c + 'a' - 'A'
		}
	}
	for _, m := range generatedMarkers {
		if bytes.Contains(lower[:n], m) {
			return true
		}
	}
	return false
}

var lineCountBufPool = sync.Pool{
	New: func() interface{} {
		buf := make([]byte, 32*1024)
		return &buf
	},
}

var scannerBufPool = sync.Pool{
	New: func() interface{} {
		buf := make([]byte, 0, defaultMaxBuf)
		return &buf
	},
}

var newlineBytes = []byte{'\n'}

// CountTotalLines efficiently counts only total lines without code/comment classification.
// Uses byte-level newline counting for maximum throughput.
// It also performs binary detection on the first chunk read.
func CountTotalLines(path, lang string) (*types.FileResult, error) {
	f, err := os.Open(path)
	if err != nil {
		return &types.FileResult{Path: path, Language: lang, Error: err.Error()}, err
	}
	defer f.Close()

	bufPtr := lineCountBufPool.Get().(*[]byte)
	defer lineCountBufPool.Put(bufPtr)
	buf := *bufPtr

	total := 0
	trailingNewline := true
	firstChunk := true
	generated := false
	for {
		n, err := f.Read(buf)
		if n > 0 {
			if firstChunk {
				firstChunk = false
				if bytes.IndexByte(buf[:n], 0) >= 0 {
					return nil, nil // signal: binary file, skip
				}
				generated = isGenerated(buf[:min(n, headSize)])
			}
			total += bytes.Count(buf[:n], newlineBytes)
			trailingNewline = buf[n-1] == '\n'
		}
		if err != nil {
			break
		}
	}
	if !trailingNewline {
		total++
	}

	return &types.FileResult{
		Path:      path,
		Language:  lang,
		Total:     total,
		Generated: generated,
	}, nil
}

// CountLines counts code, comment, blank, and (optionally) block-comment lines in a file.
// It also performs binary and generated-code detection on the file header.
func CountLines(path, lang string, commentPrefixes []string, blockStart, blockEnd string, countComplexity bool) (*types.FileResult, error) {
	f, err := os.Open(path)
	if err != nil {
		return &types.FileResult{Path: path, Language: lang, Error: err.Error()}, err
	}
	defer f.Close()

	bufPtr := scannerBufPool.Get().(*[]byte)
	defer func() {
		*bufPtr = (*bufPtr)[:0] // reset length, keep capacity
		scannerBufPool.Put(bufPtr)
	}()

	head := (*bufPtr)[:headSize]
	n, _ := io.ReadFull(f, head)
	head = head[:n]
	if bytes.IndexByte(head, 0) >= 0 {
		return nil, nil // binary file, skip
	}
	result := &types.FileResult{
		Path:      path,
		Language:  lang,
		Generated: isGenerated(head),
	}
	if _, err := f.Seek(0, io.SeekStart); err != nil {
		return &types.FileResult{Path: path, Language: lang, Error: err.Error()}, err
	}

	s := bufio.NewScanner(f)
	s.Buffer(*bufPtr, defaultMaxBuf)

	inBlock := false
	hasBlockComments := blockStart != "" && blockEnd != ""

	for s.Scan() {
		line := s.Text()
		trimmed := strings.TrimSpace(line)

		if trimmed == "" {
			result.Blank++
			continue
		}

		// Only lines that start with a block comment count as comments, so code with a
		// trailing comment (or a string such as "src/*.go") stays code.
		if hasBlockComments {
			if inBlock {
				result.Comment++
				if strings.Contains(trimmed, blockEnd) {
					inBlock = false
				}
				continue
			}
			if strings.HasPrefix(trimmed, blockStart) {
				result.Comment++
				// Search after the opener so identical delimiters (Python """) work.
				inBlock = !strings.Contains(trimmed[len(blockStart):], blockEnd)
				continue
			}
		}

		isComment := false
		for _, prefix := range commentPrefixes {
			if strings.HasPrefix(trimmed, prefix) {
				isComment = true
				break
			}
		}

		if isComment {
			result.Comment++
		} else {
			result.Code++
			if countComplexity {
				result.Complexity += countBranchKeywords(trimmed)
			}
		}
	}

	if err := s.Err(); err != nil {
		result.Error = err.Error()
	}

	result.Total = result.Code + result.Comment + result.Blank
	return result, nil
}

// branchKeywords groups keyword spellings; each group adds at most 1 per line.
var branchKeywords = [][]string{
	{"if ", "if(", "elif ", "elsif ", "unless "},
	{"for ", "for("},
	{"while ", "while("},
	{"switch ", "switch("},
	{"case "},
	{"else ", "else{"},
	{"catch ", "catch("},
	{"except ", "except:"},
}

// countBranchKeywords counts branch/loop keywords on a line.
func countBranchKeywords(line string) int {
	count := 0
	for _, group := range branchKeywords {
		for _, kw := range group {
			if hasKeyword(line, kw) {
				count++
				break
			}
		}
	}
	if strings.Contains(line, "? ") {
		count++
	}
	return count
}

// hasKeyword reports whether kw (lowercase) occurs case-insensitively in line at the
// start of a word, so "if " does not match "diff " and "case " does not match "lowercase ".
func hasKeyword(line, kw string) bool {
	n := len(kw)
	for i := 0; i+n <= len(line); i++ {
		if i > 0 && isIdentByte(line[i-1]) {
			continue
		}
		j := 0
		for j < n {
			c := line[i+j]
			if 'A' <= c && c <= 'Z' {
				c += 'a' - 'A'
			}
			if c != kw[j] {
				break
			}
			j++
		}
		if j == n {
			return true
		}
	}
	return false
}

func isIdentByte(c byte) bool {
	return c == '_' || '0' <= c && c <= '9' || 'a' <= c && c <= 'z' || 'A' <= c && c <= 'Z'
}
